//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipwreck.ViewModelUtils {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shipwreck.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Conditions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddSearchConditionTitle {
            get {
                return ResourceManager.GetString("AddSearchConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllSelected {
            get {
                return ResourceManager.GetString("AllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is invalid directory path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0IsInvalidDirectory {
            get {
                return ResourceManager.GetString("Arg0IsInvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0IsRequired {
            get {
                return ResourceManager.GetString("Arg0IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be between {1} and {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0MustBeBetweenArg1AndArg2 {
            get {
                return ResourceManager.GetString("Arg0MustBeBetweenArg1AndArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be greater than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Arg0MustBeGreaterThanOrEqualToArg1 {
            get {
                return ResourceManager.GetString("Arg0MustBeGreaterThanOrEqualToArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseDescription {
            get {
                return ResourceManager.GetString("CloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseMnemonic {
            get {
                return ResourceManager.GetString("CloseMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseTitle {
            get {
                return ResourceManager.GetString("CloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DayOperator {
            get {
                return ResourceManager.GetString("DayOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DayToken {
            get {
                return ResourceManager.GetString("DayToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard Changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard edited change(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscardChangesDescription {
            get {
                return ResourceManager.GetString("DiscardChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to discard {0} change(s)? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscardingCountArg0Confirmation {
            get {
                return ResourceManager.GetString("DiscardingCountArg0Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit items in this page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditDescriptionOfArg0 {
            get {
                return ResourceManager.GetString("EditDescriptionOfArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ends with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equal to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Except for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptForArg0 {
            get {
                return ResourceManager.GetString("ExceptForArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater than に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater than or equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HourOperator {
            get {
                return ResourceManager.GetString("HourOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HourToken {
            get {
                return ResourceManager.GetString("HourToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ,  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemSeparator {
            get {
                return ResourceManager.GetString("ItemSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemsOfCountArg0 {
            get {
                return ResourceManager.GetString("ItemsOfCountArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less than に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less than or equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinuteOperator {
            get {
                return ResourceManager.GetString("MinuteOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinuteToken {
            get {
                return ResourceManager.GetString("MinuteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MonthOperator {
            get {
                return ResourceManager.GetString("MonthOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MonthToken {
            get {
                return ResourceManager.GetString("MonthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Equal to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register the changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAndCloseDescription {
            get {
                return ResourceManager.GetString("SaveAndCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAndCloseMnemonic {
            get {
                return ResourceManager.GetString("SaveAndCloseMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAndCloseTitle {
            get {
                return ResourceManager.GetString("SaveAndCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveDescription {
            get {
                return ResourceManager.GetString("SaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveMnemonic {
            get {
                return ResourceManager.GetString("SaveMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveTitle {
            get {
                return ResourceManager.GetString("SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDefault {
            get {
                return ResourceManager.GetString("SelectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starts with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unselect All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to register {0} change(s)? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatingCountArg0Confirmation {
            get {
                return ResourceManager.GetString("UpdatingCountArg0Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YearOperator {
            get {
                return ResourceManager.GetString("YearOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YearToken {
            get {
                return ResourceManager.GetString("YearToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesTitle {
            get {
                return ResourceManager.GetString("YesTitle", resourceCulture);
            }
        }
    }
}
